name: Schema Validation

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - work

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
